version: "3"
services:    
    in-redis:
        image: redis
        ports:
            - "6379:6379"
    postgres:
        image: postgres
        ports:
            - 5442:5432
        volumes:
            - pg_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: student_management
            POSTGRES_PASSWORD: 12345
            POSTGRES_USER: testUser
            PGDATA : /var/lib/postgresql/data/pgdata
volumes:
    pg_data: